document.writeln("		<!-- 页面加载动画 -->");
document.writeln("		<div class=\'ksan\' id=\'ksan\'><svg viewbox=\'0 0 1920 1080\' preserveaspectratio=\'none\' version=\'1.1\'>");
document.writeln("				<path d=\'M0,0 C305.333333,0 625.333333,0 960,0 C1294.66667,");
document.writeln("							0 1614.66667,0 1920,0 L1920,1080 C1614.66667,");
document.writeln("							1080 1294.66667,1080 960,1080 C625.333333A,1080 305.333333,1080 0,1080 L0,0 Z\' fill=\'#c5c5c5\'>");
document.writeln("				</path>");
document.writeln("			</svg>");
document.writeln("			<div class=\'inner\'><canvas class=\'jind\' id=\'jind\' width=\'200\' height=\'200\'></canvas>");
document.writeln("				<figure><img src=\'../images/logo1.png\' alt=\'Image\'></figure><small>Loading</small>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<!-- 页面切换 -->");
document.writeln("		<div class=\'yemianqh\'><svg viewbox=\'0 0 1920 1080\' preserveaspectratio=\'none\' version=\'1.1\'>");
document.writeln("				<path d=\'M0,0 C305.333333,0 625.333333,0 960,0 C1294.66667,0 1614.66667,");
document.writeln("							0 1920,0 L1920,1080 C1614.66667,980 1294.66667,930 960,930 C625.333333,930 305.333333,980 0,1080 L0,0 Z\'");
document.writeln("					fill=\'#c5c5c5\'>");
document.writeln("				</path>");
document.writeln("			</svg></div>");
document.writeln("		<div class=\'smooth-scroll\'>");
document.writeln("			<div class=\'section-wrapper\' data-scroll-section=\'\'>");
document.writeln("				<div class=\'search-box\'>");
document.writeln("					<div class=\'container\'>");
document.writeln("						<div class=\'form\'>");
document.writeln("							<h3>搜索 青铜器</h3><input type=\'search\' placeholder=\'你想搜索的青铜器？\'><input type=\'submit\' value=\'搜索\'>");
document.writeln("						</div>");
document.writeln("						<div class=\'search-events\'>");
document.writeln("							<ul>");
document.writeln("								<li>");
document.writeln("									<h5><a href=\'#\'>后母戊鼎</small>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<h5><a href=\'#\'>四羊方尊</small>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<h5><a href=\'#\'>越王勾践剑</small>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<!-- 侧边栏图片 -->");
document.writeln("				<aside class=\'side-widget\'><svg viewbox=\'0 0 600 1080\' preserveaspectratio=\'none\' version=\'1.1\'>");
document.writeln("						<path d=\'M540,1080H0V0h540c0,179.85,0,359.7,0,539.54C540,719.7,540,899.85,540,1080z\'");
document.writeln("							fill=\'#ADD8E6\'></path>");
document.writeln("					</svg>");
document.writeln("					<figure class=\'logo\'><img src=\'../images/logo1.png\' alt=\'Image\'></figure>");
document.writeln("					<div class=\'inner\'>");
document.writeln("						<div class=\'widget\'>");
document.writeln("							<figure><img id=\'rd\' src=\'\' alt=\'\'></figure>");
document.writeln("							<figcaption id=\'rp\'></figcaption>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</aside>");
document.writeln("				<nav class=\'navbar\'>");
document.writeln("					<div class=\'logo\'><a href=\'\'><img src=\'../images/logo1.png\' alt=\'Image\'></a></div>");
document.writeln("					<div class=\'custom-menu\'>");
document.writeln("");
document.writeln("					</div>");
document.writeln("					<div class=\'site-menu\'>");
document.writeln("						<ul>");
document.writeln("							<li><a href=\'../index.html\'>首页</a></li>");
document.writeln("							<li><a href=\'../EJ/3D.html\'>3D展览区</a></li>");
document.writeln("							<li><a href=\'../EJ/shouc.html\'>本站收藏区</a></li>");
document.writeln("							<li><a href=\'../EJ/contact.html\'>联系我们</a></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'search-button\'><i class=\'bi bi-search\'></i></div>");
document.writeln("					<div class=\'lift-menu\'><svg class=\'lift\' width=\'30\' height=\'30\' viewbox=\'0 0 30 30\'>");
document.writeln("							<path class=\'line line-top\' d=\'M0,9h30\'></path>");
document.writeln("							<path class=\'line line-center\' d=\'M0,15h30\'></path>");
document.writeln("							<path class=\'line line-bottom\' d=\'M0,21h30\'></path>");
document.writeln("						</svg></div>");
document.writeln("				</nav>");